# Generated by Django 5.0.1 on 2024-01-24 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='happiness',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='nation',
            name='population',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='system',
            field=models.IntegerField(choices=[(0, 'Capitalism'), (1, 'Socialism'), (2, 'Dictatorship')]),
        ),
        migrations.AlterField(
            model_name='nationfactory',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='nations_backend.nation'),
        ),
    ]
