# Generated by Django 5.0.1 on 2024-01-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0002_alter_nation_happiness_alter_nation_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorytype',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
