# Generated by Django 5.0.1 on 2024-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0004_alter_nationfactory_factory_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='building_materials',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='metal',
            field=models.IntegerField(default=100),
        ),
    ]
