# Generated by Django 5.0.1 on 2024-01-24 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0005_alter_nation_building_materials_alter_nation_metal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationfactory',
            name='produced_commodities',
        ),
        migrations.AddField(
            model_name='nationfactory',
            name='ticks_run',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
