# Generated by Django 5.0.1 on 2024-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0009_alter_nation_happiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='taxes_to_collect',
            field=models.IntegerField(default=2500),
        ),
    ]
