# Generated by Django 5.0.1 on 2024-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0010_alter_nation_taxes_to_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='taxes_to_collect',
            field=models.IntegerField(default=0),
        ),
    ]
