# Generated by Django 5.0.1 on 2024-01-26 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0011_alter_nation_taxes_to_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='food',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='money',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='power',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='nationfactory',
            name='ticks_run',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
