# Generated by Django 5.0.1 on 2024-01-26 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0012_alter_nation_food_alter_nation_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationfactory',
            name='ticks_run',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
