# Generated by Django 5.0.1 on 2024-01-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0013_alter_nationfactory_ticks_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('icon', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations_backend.alliance')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance', to='nations_backend.nation')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations_backend.alliance')),
                ('requesting_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations_backend.nation')),
            ],
        ),
    ]
