# Generated by Django 5.0.1 on 2024-02-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceShout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('shouting_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations_backend.nation')),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='shout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nations_backend.allianceshout'),
        ),
    ]
