# Generated by Django 5.0.1 on 2024-02-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0016_allianceshout_alliance_shout'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='nations_backend.nation')),
            ],
        ),
    ]
