# Generated by Django 5.0.1 on 2024-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0017_nationbuilding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationbuilding',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
