# Generated by Django 5.0.1 on 2024-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0018_alter_nationbuilding_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='building_materials',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='food',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='nation',
            name='money',
            field=models.IntegerField(default=100000),
        ),
    ]
