# Generated by Django 5.0.1 on 2024-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0019_alter_nation_building_materials_alter_nation_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='land',
            field=models.IntegerField(default=10000),
        ),
    ]
