# Generated by Django 5.0.1 on 2024-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations_backend', '0021_nationupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='unused_land',
            field=models.IntegerField(default=10000),
        ),
    ]
